services:
    bastien59960.reactions.controller.main:
        class: bastien59960\reactions\controller\main
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@request'

    # Service pour le listener
    bastien59960.reactions.event.listener:
        class: bastien59960\reactions\event\listener
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@user'
            - '@template'
            - '@router.url_generator'
            - '@assets.manager'
        tags:
            - { name: event.listener }
