# Fichier : ext/bastien59960/reactions/config/cron.yml
#
# Ce fichier déclare explicitement les tâches cron de l'extension pour phpBB.
# Bien que le tag `cron.task` dans `services.yml` soit la méthode moderne,
# ce fichier assure une compatibilité et une déclaration claire.
#
# IMPORTANT : Le nom À GAUCHE est l'ID interne, le champ `task:` À DROITE
# doit pointer vers l'identifiant du service défini dans services.yml.

#cron.task.bastien59960.reactions.notification_task:
#    task: cron.task.bastien59960.reactions.notification_task

cron.task.bastien59960.reactions.test_task:
    task: cron.task.bastien59960.reactions.test_task